name: app_environment
channels:
  - snowflake
dependencies:
  - bcrypt
  - numpy
  - openpyxl
  - pandas
  - plotly
  - pydeck
  - python
  - python-docx
  - regex
  - scipy
  - snowflake-snowpark-python
  - streamlit
  - streamlit-extras
  - textdistance
